# Шаталин Александр Андреевич
## Рабочая тетрадь 2

### 1.3.1 Задание

In [6]:
import numpy as np

arr = np.zeros(64).reshape(8, 8)

for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 1:
            arr[i][j] = 1
        
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### 1.3.2 Задание

In [7]:
arr = np.array([])
for n in range(5):
    arr = np.append(arr, np.arange(0, 5))
print(arr.reshape(5, 5))

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 1.3.3 Задание

In [8]:
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.41118444 0.36615275 0.78432368]
  [0.71192215 0.69611137 0.50482036]
  [0.08075104 0.11777309 0.43865456]]

 [[0.26044909 0.29138231 0.63875063]
  [0.19920276 0.95697901 0.00946943]
  [0.94602386 0.72464599 0.83162658]]

 [[0.69383588 0.17884081 0.57705154]
  [0.82150765 0.78007483 0.54702702]
  [0.15171869 0.68492783 0.49338124]]]


### 1.3.4 Задание

In [4]:
arr = np.zeros(64).reshape(8, 8)

for i in range(8):
    for j in range(8):
        if i == 0 or j == 0 or i == 7 or j == 7:
            arr[i][j] = 1
            
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


### 1.3.5 Задание

In [5]:
arr = np.random.random((15))
print(-np.sort(-arr))

[0.96025464 0.88536983 0.83200804 0.81711251 0.8163404  0.60845443
 0.59871948 0.52962934 0.4663637  0.43408787 0.27492759 0.25457269
 0.12114326 0.07679403 0.03278733]


### 1.3.6 Задание

In [75]:
arr = np.arange(36).reshape(6, 6)
print (arr.shape, arr.ndim, arr.size)

(6, 6) 2 36


### 2.3.1 Задание

In [82]:
import pandas as pd

ser = pd.Series({'a': 1.868, 'b': -20.843, 'c': 3})

print((ser[0] - ser[1])**2)

515.7895209999999


### 2.3.2 Задание

In [89]:
df = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/main/adult.csv")
df.head()

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Other    Male              40   
4     Prof-specialty           Wife  Other  Female              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K  
4          Other        0         <=50K

### 2.3.3 Задание

In [88]:
df.head(2)
df.tail(3)
df.shape
df.describe

<bound method NDFrame.describe of        age         workclass  education_num      marital_status  \
0       39         State-gov             13       Never-married   
1       50  Self-emp-not-inc             13  Married-civ-spouse   
2       38           Private              9            Divorced   
3       53           Private              7  Married-civ-spouse   
4       28           Private             13  Married-civ-spouse   
...    ...               ...            ...                 ...   
45217   33           Private             13       Never-married   
45218   39           Private             13            Divorced   
45219   38           Private             13  Married-civ-spouse   
45220   44           Private             13            Divorced   
45221   35      Self-emp-inc             13  Married-civ-spouse   

              occupation   relationship   race  gender  hours_per_week  \
0           Adm-clerical  Not-in-family  White    Male              40   
1        Exec

In [90]:
df.iloc[1:4]

age         workclass  education_num      marital_status  \
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   

          occupation   relationship   race gender  hours_per_week  \
1    Exec-managerial        Husband  White   Male              13   
2  Handlers-cleaners  Not-in-family  White   Male              40   
3  Handlers-cleaners        Husband  Other   Male              40   

  native_country  capital income_status  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K

In [91]:
df[df['marital_status'] == 'Divorced'].head(2)

age         workclass  education_num marital_status         occupation  \
2    38           Private              9       Divorced  Handlers-cleaners   
18   43  Self-emp-not-inc             14       Divorced    Exec-managerial   

     relationship   race  gender  hours_per_week native_country  capital  \
2   Not-in-family  White    Male              40  United-States        0   
18      Unmarried  White  Female              45  United-States        0   

   income_status  
2          <=50K  
18          >50K

### 3.3.2 Задание

In [93]:
df = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')
df.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования

In [110]:
from sklearn import preprocessing

feat_length = np.array(df['sepal_length_cm']) 
feat_width = np.array(df['sepal_width_cm'])

minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
z_scale = preprocessing.StandardScaler()

scaled_feat_length = minmax_scale.fit_transform(feat_length.reshape(-1, 1))
scaled_feat_width = z_scale.fit_transform(feat_width.reshape(-1, 1))

print(scaled_feat_length[0:5], '\n'*2, scaled_feat_width[0:5])

[[0.22222222]
 [0.16666667]
 [0.11111111]
 [0.08333333]
 [0.19444444]] 

 [[ 1.03205722]
 [-0.1249576 ]
 [ 0.33784833]
 [ 0.10644536]
 [ 1.26346019]]
